[project]
name = "rit-website"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django~=5.2.0",
    "django-environ>=0.14.0",
    "psycopg[binary]>=3.3.4",
    "wagtail~=7.4.0",
]

[dependency-groups]
dev = [
    "django-stubs>=6.1.0",
    "factory-boy>=3.3.3",
    "mypy>=2.3.1",
    "pytest>=9.1.1",
    "pytest-django>=4.14.0",
    "ruff>=0.16.5",
    "testcontainers>=4.15.0",
]
