# Generated by Django 5.2.17 on 2026-09-01 01:10

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Página de inicio'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 9), ('marquee', 11), ('nosotros', 18), ('services', 22), ('partners', 24), ('stats', 30), ('cases', 34), ('contact', 39)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Texto antes del highlight (gradiente)'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Texto resaltado con gradiente'}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Frase corta bajo el título'}), 3: ('wagtail.blocks.CharBlock', (), {'default': '01', 'help_text': 'Índice del slide (01, 02…)'}), 4: ('wagtail.blocks.TextBlock', (), {'help_text': 'Párrafo lateral del slide'}), 5: ('wagtail.blocks.StructBlock', [[('pre', 0), ('hi', 1), ('kicker', 2), ('index', 3), ('sub', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'min_num': 1}), 7: ('wagtail.blocks.CharBlock', (), {}), 8: ('wagtail.blocks.ListBlock', (7,), {'help_text': 'Hasta 3 pills', 'max_num': 3}), 9: ('wagtail.blocks.StructBlock', [[('slides', 6), ('pills', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (7,), {'help_text': 'Tecnologías del marquee'}), 11: ('wagtail.blocks.StructBlock', [[('items', 10)]], {}), 12: ('wagtail.blocks.TextBlock', (), {}), 13: ('wagtail.blocks.ListBlock', (12,), {'help_text': 'Párrafos de presentación', 'min_num': 1}), 14: ('wagtail.blocks.CharBlock', (), {'default': '01'}), 15: ('wagtail.blocks.CharBlock', (), {'default': 'server', 'help_text': 'server | shield | cloud | chat | headset | …'}), 16: ('wagtail.blocks.StructBlock', [[('num', 14), ('title', 7), ('body', 12), ('icon', 15)]], {}), 17: ('wagtail.blocks.ListBlock', (16,), {'help_text': 'Tarjetas de valor', 'min_num': 1}), 18: ('wagtail.blocks.StructBlock', [[('leads', 13), ('cards', 17)]], {}), 19: ('wagtail.blocks.CharBlock', (), {'default': 'server'}), 20: ('wagtail.blocks.StructBlock', [[('n', 14), ('tag', 7), ('title', 7), ('body', 12), ('icon', 19)]], {}), 21: ('wagtail.blocks.ListBlock', (20,), {'help_text': 'Máx. 4 (carrusel CSS atado a 4)', 'max_num': 4, 'min_num': 1}), 22: ('wagtail.blocks.StructBlock', [[('cards', 21)]], {}), 23: ('wagtail.blocks.ListBlock', (7,), {}), 24: ('wagtail.blocks.StructBlock', [[('row_a', 23), ('row_b', 23)]], {}), 25: ('wagtail.blocks.IntegerBlock', (), {}), 26: ('wagtail.blocks.CharBlock', (), {'default': '', 'help_text': "Prefijo, ej. '+'", 'required': False}), 27: ('wagtail.blocks.CharBlock', (), {'default': '', 'help_text': "Sufijo, ej. '%'", 'required': False}), 28: ('wagtail.blocks.StructBlock', [[('count', 25), ('pre', 26), ('post', 27), ('label', 7)]], {}), 29: ('wagtail.blocks.ListBlock', (28,), {'min_num': 1}), 30: ('wagtail.blocks.StructBlock', [[('stats', 29)]], {}), 31: ('wagtail.blocks.CharBlock', (), {'help_text': "Métrica de resultado, ej. '-30% en costos'"}), 32: ('wagtail.blocks.StructBlock', [[('tag', 7), ('title', 7), ('body', 12), ('result', 31)]], {}), 33: ('wagtail.blocks.ListBlock', (32,), {'min_num': 1}), 34: ('wagtail.blocks.StructBlock', [[('cases', 33)]], {}), 35: ('wagtail.blocks.CharBlock', (), {'help_text': 'Clave, ej. EMAIL'}), 36: ('wagtail.blocks.CharBlock', (), {'help_text': 'Valor, ej. hola@ritenterprise.com.co'}), 37: ('wagtail.blocks.StructBlock', [[('k', 35), ('v', 36)]], {}), 38: ('wagtail.blocks.ListBlock', (37,), {'help_text': 'Datos de contacto'}), 39: ('wagtail.blocks.StructBlock', [[('rows', 38)]], {})}),
        ),
    ]
