# Generated by Django 5.2.17 on 2026-09-15 22:16

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_homepage_body"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="NosotrosPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("page_hero", 6),
                            ("story", 10),
                            ("stats", 16),
                            ("sectors", 21),
                            ("mission_vision", 22),
                            ("values", 25),
                            ("cta", 28),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Etiqueta superior, ej. 'Nosotros'"},
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Título (parte normal)"},
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Parte resaltada con gradiente",
                                    "required": False,
                                },
                            ),
                            3: ("wagtail.blocks.TextBlock", (), {"required": False}),
                            4: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "/contacto/", "required": False},
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("badge", 0),
                                        ("title_pre", 1),
                                        ("title_hi", 2),
                                        ("lead", 3),
                                        ("cta_label", 4),
                                        ("cta_href", 5),
                                    ]
                                ],
                                {},
                            ),
                            7: ("wagtail.blocks.CharBlock", (), {}),
                            8: ("wagtail.blocks.TextBlock", (), {}),
                            9: ("wagtail.blocks.ListBlock", (8,), {"min_num": 1}),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("badge", 7),
                                        ("title_pre", 7),
                                        ("title_hi", 4),
                                        ("paragraphs", 9),
                                    ]
                                ],
                                {},
                            ),
                            11: ("wagtail.blocks.IntegerBlock", (), {}),
                            12: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "",
                                    "help_text": "Prefijo, ej. '+'",
                                    "required": False,
                                },
                            ),
                            13: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "",
                                    "help_text": "Sufijo, ej. '%'",
                                    "required": False,
                                },
                            ),
                            14: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("count", 11),
                                        ("pre", 12),
                                        ("post", 13),
                                        ("label", 7),
                                    ]
                                ],
                                {},
                            ),
                            15: ("wagtail.blocks.ListBlock", (14,), {"min_num": 1}),
                            16: (
                                "wagtail.blocks.StructBlock",
                                [[("badge", 7), ("title", 7), ("stats", 15)]],
                                {},
                            ),
                            17: ("wagtail.blocks.CharBlock", (), {"default": "01"}),
                            18: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Tecnologías / etiqueta",
                                    "required": False,
                                },
                            ),
                            19: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("num", 17),
                                        ("title", 7),
                                        ("tag", 18),
                                        ("points", 9),
                                    ]
                                ],
                                {},
                            ),
                            20: ("wagtail.blocks.ListBlock", (19,), {"min_num": 1}),
                            21: (
                                "wagtail.blocks.StructBlock",
                                [[("badge", 7), ("title", 7), ("cards", 20)]],
                                {},
                            ),
                            22: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("badge", 7),
                                        ("title_pre", 7),
                                        ("title_hi", 4),
                                        ("mission", 8),
                                        ("vision", 8),
                                    ]
                                ],
                                {},
                            ),
                            23: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 7), ("body", 8)]],
                                {},
                            ),
                            24: ("wagtail.blocks.ListBlock", (23,), {"min_num": 1}),
                            25: (
                                "wagtail.blocks.StructBlock",
                                [[("badge", 7), ("title", 7), ("items", 24)]],
                                {},
                            ),
                            26: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Contáctenos ahora"},
                            ),
                            27: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "/contacto/"},
                            ),
                            28: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 7),
                                        ("body", 3),
                                        ("cta_label", 26),
                                        ("cta_href", 27),
                                    ]
                                ],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "verbose_name": "Página Nosotros",
            },
            bases=("wagtailcore.page",),
        ),
    ]
