# Generated by Django 5.2.17 on 2026-09-15 23:48

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_create_nosotros"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactoPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("page_hero", 6),
                            ("contact_info", 13),
                            ("contact_form", 16),
                            ("map", 18),
                            ("cta", 21),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Etiqueta superior, ej. 'Nosotros'"},
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Título (parte normal)"},
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Parte resaltada con gradiente",
                                    "required": False,
                                },
                            ),
                            3: ("wagtail.blocks.TextBlock", (), {"required": False}),
                            4: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "/contacto/", "required": False},
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("badge", 0),
                                        ("title_pre", 1),
                                        ("title_hi", 2),
                                        ("lead", 3),
                                        ("cta_label", 4),
                                        ("cta_href", 5),
                                    ]
                                ],
                                {},
                            ),
                            7: ("wagtail.blocks.CharBlock", (), {}),
                            8: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Etiqueta, ej. Oficina"},
                            ),
                            9: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Valor, ej. AV Kra 9 # 115-06 OF 1207"},
                            ),
                            10: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Enlace opcional (mailto:, tel:, URL)",
                                    "required": False,
                                },
                            ),
                            11: (
                                "wagtail.blocks.StructBlock",
                                [[("k", 8), ("v", 9), ("href", 10)]],
                                {},
                            ),
                            12: ("wagtail.blocks.ListBlock", (11,), {"min_num": 1}),
                            13: (
                                "wagtail.blocks.StructBlock",
                                [[("badge", 7), ("title", 7), ("cards", 12)]],
                                {},
                            ),
                            14: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Nota legal (Habeas Data)",
                                    "required": False,
                                },
                            ),
                            15: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "/politica-de-privacidad/",
                                    "required": False,
                                },
                            ),
                            16: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("badge", 7),
                                        ("title", 7),
                                        ("note", 14),
                                        ("privacy_href", 15),
                                    ]
                                ],
                                {},
                            ),
                            17: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Dirección para el mapa"},
                            ),
                            18: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 4), ("query", 17)]],
                                {},
                            ),
                            19: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Contáctenos ahora"},
                            ),
                            20: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "/contacto/"},
                            ),
                            21: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 7),
                                        ("body", 3),
                                        ("cta_label", 19),
                                        ("cta_href", 20),
                                    ]
                                ],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "verbose_name": "Página Contacto",
            },
            bases=("wagtailcore.page",),
        ),
    ]
