# Generated by Django 5.2.17 on 2026-09-16 17:44

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_create_contacto"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolucionesIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("page_hero", 6), ("cta", 10)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Etiqueta superior, ej. 'Nosotros'"},
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Título (parte normal)"},
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Parte resaltada con gradiente",
                                    "required": False,
                                },
                            ),
                            3: ("wagtail.blocks.TextBlock", (), {"required": False}),
                            4: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "/contacto/", "required": False},
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("badge", 0),
                                        ("title_pre", 1),
                                        ("title_hi", 2),
                                        ("lead", 3),
                                        ("cta_label", 4),
                                        ("cta_href", 5),
                                    ]
                                ],
                                {},
                            ),
                            7: ("wagtail.blocks.CharBlock", (), {}),
                            8: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Contáctenos ahora"},
                            ),
                            9: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "/contacto/"},
                            ),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 7),
                                        ("body", 3),
                                        ("cta_label", 8),
                                        ("cta_href", 9),
                                    ]
                                ],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "verbose_name": "Índice de Soluciones",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="SolucionPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("page_hero", 6),
                            ("cards", 13),
                            ("checklist", 15),
                            ("accordion", 18),
                            ("highlight", 19),
                            ("cta", 22),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Etiqueta superior, ej. 'Nosotros'"},
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Título (parte normal)"},
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Parte resaltada con gradiente",
                                    "required": False,
                                },
                            ),
                            3: ("wagtail.blocks.TextBlock", (), {"required": False}),
                            4: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "/contacto/", "required": False},
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("badge", 0),
                                        ("title_pre", 1),
                                        ("title_hi", 2),
                                        ("lead", 3),
                                        ("cta_label", 4),
                                        ("cta_href", 5),
                                    ]
                                ],
                                {},
                            ),
                            7: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Etiqueta superior de la tarjeta",
                                    "required": False,
                                },
                            ),
                            8: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "server", "required": False},
                            ),
                            9: ("wagtail.blocks.CharBlock", (), {}),
                            10: ("wagtail.blocks.TextBlock", (), {}),
                            11: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("badge", 7),
                                        ("icon", 8),
                                        ("title", 9),
                                        ("body", 10),
                                        ("cta_label", 4),
                                        ("cta_href", 4),
                                    ]
                                ],
                                {},
                            ),
                            12: ("wagtail.blocks.ListBlock", (11,), {"min_num": 1}),
                            13: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("badge", 4),
                                        ("title", 4),
                                        ("intro", 3),
                                        ("cards", 12),
                                    ]
                                ],
                                {},
                            ),
                            14: ("wagtail.blocks.ListBlock", (9,), {"min_num": 1}),
                            15: (
                                "wagtail.blocks.StructBlock",
                                [[("badge", 4), ("title", 4), ("items", 14)]],
                                {},
                            ),
                            16: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 9), ("body", 10)]],
                                {},
                            ),
                            17: ("wagtail.blocks.ListBlock", (16,), {"min_num": 1}),
                            18: (
                                "wagtail.blocks.StructBlock",
                                [[("badge", 4), ("title", 4), ("items", 17)]],
                                {},
                            ),
                            19: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("badge", 4),
                                        ("title", 9),
                                        ("body", 3),
                                        ("cta_label", 4),
                                        ("cta_href", 4),
                                    ]
                                ],
                                {},
                            ),
                            20: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Contáctenos ahora"},
                            ),
                            21: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "/contacto/"},
                            ),
                            22: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 9),
                                        ("body", 3),
                                        ("cta_label", 20),
                                        ("cta_href", 21),
                                    ]
                                ],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "verbose_name": "Página de Solución",
            },
            bases=("wagtailcore.page",),
        ),
    ]
