# Generated by Django 5.2.17 on 2026-09-16 19:34

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_create_soluciones"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solucionpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("page_hero", 6),
                    ("cards", 13),
                    ("checklist", 15),
                    ("accordion", 18),
                    ("highlight", 20),
                    ("badges", 21),
                    ("allies", 21),
                    ("cta", 24),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Etiqueta superior, ej. 'Nosotros'"},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Título (parte normal)"},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Parte resaltada con gradiente",
                            "required": False,
                        },
                    ),
                    3: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    4: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "/contacto/", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 0),
                                ("title_pre", 1),
                                ("title_hi", 2),
                                ("lead", 3),
                                ("cta_label", 4),
                                ("cta_href", 5),
                            ]
                        ],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Etiqueta superior de la tarjeta",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "server", "required": False},
                    ),
                    9: ("wagtail.blocks.CharBlock", (), {}),
                    10: ("wagtail.blocks.TextBlock", (), {}),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 7),
                                ("icon", 8),
                                ("title", 9),
                                ("body", 10),
                                ("cta_label", 4),
                                ("cta_href", 4),
                            ]
                        ],
                        {},
                    ),
                    12: ("wagtail.blocks.ListBlock", (11,), {"min_num": 1}),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("badge", 4), ("title", 4), ("intro", 3), ("cards", 12)]],
                        {},
                    ),
                    14: ("wagtail.blocks.ListBlock", (9,), {"min_num": 1}),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("badge", 4), ("title", 4), ("items", 14)]],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 9), ("body", 10)]],
                        {},
                    ),
                    17: ("wagtail.blocks.ListBlock", (16,), {"min_num": 1}),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("badge", 4), ("title", 4), ("items", 17)]],
                        {},
                    ),
                    19: ("wagtail.blocks.ListBlock", (9,), {"required": False}),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 4),
                                ("title", 9),
                                ("body", 3),
                                ("bullets", 19),
                                ("cta_label", 4),
                                ("cta_href", 4),
                            ]
                        ],
                        {},
                    ),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [[("badge", 4), ("title", 4), ("subtitle", 4), ("items", 14)]],
                        {},
                    ),
                    22: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Contáctenos ahora"},
                    ),
                    23: ("wagtail.blocks.CharBlock", (), {"default": "/contacto/"}),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 9),
                                ("body", 3),
                                ("cta_label", 22),
                                ("cta_href", 23),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
