# Generated by Django 5.2.17 on 2026-09-16 23:55

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_create_ciberseguridad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solucionpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("page_hero", 6),
                    ("story", 10),
                    ("cards", 15),
                    ("checklist", 17),
                    ("accordion", 20),
                    ("highlight", 22),
                    ("badges", 23),
                    ("allies", 23),
                    ("timeline", 26),
                    ("split_bullets", 27),
                    ("quote", 28),
                    ("cta", 31),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Etiqueta superior, ej. 'Nosotros'"},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Título (parte normal)"},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Parte resaltada con gradiente",
                            "required": False,
                        },
                    ),
                    3: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    4: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "/contacto/", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 0),
                                ("title_pre", 1),
                                ("title_hi", 2),
                                ("lead", 3),
                                ("cta_label", 4),
                                ("cta_href", 5),
                            ]
                        ],
                        {},
                    ),
                    7: ("wagtail.blocks.CharBlock", (), {}),
                    8: ("wagtail.blocks.TextBlock", (), {}),
                    9: ("wagtail.blocks.ListBlock", (8,), {"min_num": 1}),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 7),
                                ("title_pre", 7),
                                ("title_hi", 4),
                                ("paragraphs", 9),
                            ]
                        ],
                        {},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Etiqueta superior de la tarjeta",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "server", "required": False},
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 11),
                                ("icon", 12),
                                ("title", 7),
                                ("body", 8),
                                ("cta_label", 4),
                                ("cta_href", 4),
                            ]
                        ],
                        {},
                    ),
                    14: ("wagtail.blocks.ListBlock", (13,), {"min_num": 1}),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("badge", 4), ("title", 4), ("intro", 3), ("cards", 14)]],
                        {},
                    ),
                    16: ("wagtail.blocks.ListBlock", (7,), {"min_num": 1}),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("badge", 4), ("title", 4), ("items", 16)]],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 7), ("body", 8)]],
                        {},
                    ),
                    19: ("wagtail.blocks.ListBlock", (18,), {"min_num": 1}),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("badge", 4), ("title", 4), ("items", 19)]],
                        {},
                    ),
                    21: ("wagtail.blocks.ListBlock", (7,), {"required": False}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 4),
                                ("title", 7),
                                ("body", 3),
                                ("bullets", 21),
                                ("cta_label", 4),
                                ("cta_href", 4),
                            ]
                        ],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("badge", 4), ("title", 4), ("subtitle", 4), ("items", 16)]],
                        {},
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 7), ("body", 3)]],
                        {},
                    ),
                    25: ("wagtail.blocks.ListBlock", (24,), {"min_num": 1}),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [[("badge", 4), ("title", 4), ("steps", 25)]],
                        {},
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 4),
                                ("title", 4),
                                ("intro", 3),
                                ("items", 19),
                                ("note", 3),
                            ]
                        ],
                        {},
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("badge", 4), ("text", 8)]],
                        {},
                    ),
                    29: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Contáctenos ahora"},
                    ),
                    30: ("wagtail.blocks.CharBlock", (), {"default": "/contacto/"}),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 7),
                                ("body", 3),
                                ("cta_label", 29),
                                ("cta_href", 30),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
