# Generated by Django 5.2.17 on 2026-10-09 15:56

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0016_create_soluciones_restantes"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="InteriorPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("page_hero", 6),
                            ("story", 10),
                            ("cards", 15),
                            ("tabs", 19),
                            ("checklist", 21),
                            ("accordion", 24),
                            ("highlight", 26),
                            ("badges", 27),
                            ("allies", 27),
                            ("timeline", 30),
                            ("split_bullets", 31),
                            ("quote", 32),
                            ("cta", 35),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Etiqueta superior, ej. 'Nosotros'"},
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Título (parte normal)"},
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Parte resaltada con gradiente",
                                    "required": False,
                                },
                            ),
                            3: ("wagtail.blocks.TextBlock", (), {"required": False}),
                            4: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "/contacto/", "required": False},
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("badge", 0),
                                        ("title_pre", 1),
                                        ("title_hi", 2),
                                        ("lead", 3),
                                        ("cta_label", 4),
                                        ("cta_href", 5),
                                    ]
                                ],
                                {},
                            ),
                            7: ("wagtail.blocks.CharBlock", (), {}),
                            8: ("wagtail.blocks.TextBlock", (), {}),
                            9: ("wagtail.blocks.ListBlock", (8,), {"min_num": 1}),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("badge", 7),
                                        ("title_pre", 7),
                                        ("title_hi", 4),
                                        ("paragraphs", 9),
                                    ]
                                ],
                                {},
                            ),
                            11: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Etiqueta superior de la tarjeta",
                                    "required": False,
                                },
                            ),
                            12: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "server", "required": False},
                            ),
                            13: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("badge", 11),
                                        ("icon", 12),
                                        ("title", 7),
                                        ("body", 8),
                                        ("cta_label", 4),
                                        ("cta_href", 4),
                                    ]
                                ],
                                {},
                            ),
                            14: ("wagtail.blocks.ListBlock", (13,), {"min_num": 1}),
                            15: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("badge", 4),
                                        ("title", 4),
                                        ("intro", 3),
                                        ("cards", 14),
                                    ]
                                ],
                                {},
                            ),
                            16: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Texto de la pestaña"},
                            ),
                            17: (
                                "wagtail.blocks.StructBlock",
                                [[("label", 16), ("title", 7), ("body", 8)]],
                                {},
                            ),
                            18: ("wagtail.blocks.ListBlock", (17,), {"min_num": 1}),
                            19: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("badge", 4),
                                        ("title", 4),
                                        ("subtitle", 4),
                                        ("tabs", 18),
                                    ]
                                ],
                                {},
                            ),
                            20: ("wagtail.blocks.ListBlock", (7,), {"min_num": 1}),
                            21: (
                                "wagtail.blocks.StructBlock",
                                [[("badge", 4), ("title", 4), ("items", 20)]],
                                {},
                            ),
                            22: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 7), ("body", 8)]],
                                {},
                            ),
                            23: ("wagtail.blocks.ListBlock", (22,), {"min_num": 1}),
                            24: (
                                "wagtail.blocks.StructBlock",
                                [[("badge", 4), ("title", 4), ("items", 23)]],
                                {},
                            ),
                            25: ("wagtail.blocks.ListBlock", (7,), {"required": False}),
                            26: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("badge", 4),
                                        ("title", 7),
                                        ("body", 3),
                                        ("bullets", 25),
                                        ("cta_label", 4),
                                        ("cta_href", 4),
                                    ]
                                ],
                                {},
                            ),
                            27: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("badge", 4),
                                        ("title", 4),
                                        ("subtitle", 4),
                                        ("items", 20),
                                    ]
                                ],
                                {},
                            ),
                            28: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 7), ("body", 3)]],
                                {},
                            ),
                            29: ("wagtail.blocks.ListBlock", (28,), {"min_num": 1}),
                            30: (
                                "wagtail.blocks.StructBlock",
                                [[("badge", 4), ("title", 4), ("steps", 29)]],
                                {},
                            ),
                            31: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("badge", 4),
                                        ("title", 4),
                                        ("intro", 3),
                                        ("items", 23),
                                        ("note", 3),
                                    ]
                                ],
                                {},
                            ),
                            32: (
                                "wagtail.blocks.StructBlock",
                                [[("badge", 4), ("text", 8)]],
                                {},
                            ),
                            33: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Contáctenos ahora"},
                            ),
                            34: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "/contacto/"},
                            ),
                            35: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 7),
                                        ("body", 3),
                                        ("cta_label", 33),
                                        ("cta_href", 34),
                                    ]
                                ],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "verbose_name": "Página interior",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="SeccionIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("page_hero", 6), ("cta", 10)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Etiqueta superior, ej. 'Nosotros'"},
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Título (parte normal)"},
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Parte resaltada con gradiente",
                                    "required": False,
                                },
                            ),
                            3: ("wagtail.blocks.TextBlock", (), {"required": False}),
                            4: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "/contacto/", "required": False},
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("badge", 0),
                                        ("title_pre", 1),
                                        ("title_hi", 2),
                                        ("lead", 3),
                                        ("cta_label", 4),
                                        ("cta_href", 5),
                                    ]
                                ],
                                {},
                            ),
                            7: ("wagtail.blocks.CharBlock", (), {}),
                            8: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Contáctenos ahora"},
                            ),
                            9: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "/contacto/"},
                            ),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 7),
                                        ("body", 3),
                                        ("cta_label", 8),
                                        ("cta_href", 9),
                                    ]
                                ],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "verbose_name": "Índice de sección",
            },
            bases=("wagtailcore.page",),
        ),
    ]
